export { default as useGetApi } from './useGetApi'
export { default as useDeleteApi } from './useDeleteApi'
export { default as usePostApi } from './usePostApi'
export { default as usePutApi } from './usePutApi'
export { default as useUploadApi } from './useUploadApi'
export { default as useAxiosRequest } from './useAxiosRequest'
export { default as useRequest } from './useRequest'
export { default as useDetailRequest } from './useDetailRequest'
